# Generated by Django 4.1.7 on 2023-02-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_rename_book_libroinstance_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='name',
            new_name='title',
        ),
    ]
