# Generated by Django 4.1.7 on 2023-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_rename_name_libro_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Died'),
        ),
    ]
