# Generated by Django 4.1.7 on 2023-02-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_autor_date_of_birth_alter_autor_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='libroinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Mantenimiento'), ('o', 'On loan'), ('a', 'Aviable'), ('r', 'Reserved')], default='m', help_text='Disponibilidad del libro', max_length=1),
        ),
    ]
