# Generated by Django 4.1.7 on 2023-02-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_libroinstance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libroinstance',
            options={'ordering': ['due_back']},
        ),
    ]
